// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.launchdarkly.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.launchdarkly.outputs.GetTeamMaintainer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetTeamResult {
    /**
     * @return The list of the keys of the custom roles that you have assigned to the team.
     * 
     */
    private @Nullable List<String> customRoleKeys;
    /**
     * @return The team description.
     * 
     */
    private @Nullable String description;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String key;
    /**
     * @return The list of team maintainers as [team member objects](https://www.terraform.io/docs/providers/launchdarkly/d/team_member.html).
     * 
     */
    private List<GetTeamMaintainer> maintainers;
    /**
     * @return Human readable name for the team.
     * 
     */
    private @Nullable String name;
    /**
     * @return The list of keys of the projects that the team has any write access to.
     * 
     */
    private List<String> projectKeys;

    private GetTeamResult() {}
    /**
     * @return The list of the keys of the custom roles that you have assigned to the team.
     * 
     */
    public List<String> customRoleKeys() {
        return this.customRoleKeys == null ? List.of() : this.customRoleKeys;
    }
    /**
     * @return The team description.
     * 
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String key() {
        return this.key;
    }
    /**
     * @return The list of team maintainers as [team member objects](https://www.terraform.io/docs/providers/launchdarkly/d/team_member.html).
     * 
     */
    public List<GetTeamMaintainer> maintainers() {
        return this.maintainers;
    }
    /**
     * @return Human readable name for the team.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return The list of keys of the projects that the team has any write access to.
     * 
     */
    public List<String> projectKeys() {
        return this.projectKeys;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTeamResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> customRoleKeys;
        private @Nullable String description;
        private String id;
        private String key;
        private List<GetTeamMaintainer> maintainers;
        private @Nullable String name;
        private List<String> projectKeys;
        public Builder() {}
        public Builder(GetTeamResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.customRoleKeys = defaults.customRoleKeys;
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.key = defaults.key;
    	      this.maintainers = defaults.maintainers;
    	      this.name = defaults.name;
    	      this.projectKeys = defaults.projectKeys;
        }

        @CustomType.Setter
        public Builder customRoleKeys(@Nullable List<String> customRoleKeys) {
            this.customRoleKeys = customRoleKeys;
            return this;
        }
        public Builder customRoleKeys(String... customRoleKeys) {
            return customRoleKeys(List.of(customRoleKeys));
        }
        @CustomType.Setter
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder key(String key) {
            this.key = Objects.requireNonNull(key);
            return this;
        }
        @CustomType.Setter
        public Builder maintainers(List<GetTeamMaintainer> maintainers) {
            this.maintainers = Objects.requireNonNull(maintainers);
            return this;
        }
        public Builder maintainers(GetTeamMaintainer... maintainers) {
            return maintainers(List.of(maintainers));
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder projectKeys(List<String> projectKeys) {
            this.projectKeys = Objects.requireNonNull(projectKeys);
            return this;
        }
        public Builder projectKeys(String... projectKeys) {
            return projectKeys(List.of(projectKeys));
        }
        public GetTeamResult build() {
            final var o = new GetTeamResult();
            o.customRoleKeys = customRoleKeys;
            o.description = description;
            o.id = id;
            o.key = key;
            o.maintainers = maintainers;
            o.name = name;
            o.projectKeys = projectKeys;
            return o;
        }
    }
}
