// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.launchdarkly.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.Objects;


public final class FeatureFlagDefaultsArgs extends com.pulumi.resources.ResourceArgs {

    public static final FeatureFlagDefaultsArgs Empty = new FeatureFlagDefaultsArgs();

    /**
     * The index of the variation the flag will default to in all new environments when off.
     * 
     */
    @Import(name="offVariation", required=true)
    private Output<Integer> offVariation;

    /**
     * @return The index of the variation the flag will default to in all new environments when off.
     * 
     */
    public Output<Integer> offVariation() {
        return this.offVariation;
    }

    /**
     * The index of the variation the flag will default to in all new environments when on.
     * 
     */
    @Import(name="onVariation", required=true)
    private Output<Integer> onVariation;

    /**
     * @return The index of the variation the flag will default to in all new environments when on.
     * 
     */
    public Output<Integer> onVariation() {
        return this.onVariation;
    }

    private FeatureFlagDefaultsArgs() {}

    private FeatureFlagDefaultsArgs(FeatureFlagDefaultsArgs $) {
        this.offVariation = $.offVariation;
        this.onVariation = $.onVariation;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FeatureFlagDefaultsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FeatureFlagDefaultsArgs $;

        public Builder() {
            $ = new FeatureFlagDefaultsArgs();
        }

        public Builder(FeatureFlagDefaultsArgs defaults) {
            $ = new FeatureFlagDefaultsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param offVariation The index of the variation the flag will default to in all new environments when off.
         * 
         * @return builder
         * 
         */
        public Builder offVariation(Output<Integer> offVariation) {
            $.offVariation = offVariation;
            return this;
        }

        /**
         * @param offVariation The index of the variation the flag will default to in all new environments when off.
         * 
         * @return builder
         * 
         */
        public Builder offVariation(Integer offVariation) {
            return offVariation(Output.of(offVariation));
        }

        /**
         * @param onVariation The index of the variation the flag will default to in all new environments when on.
         * 
         * @return builder
         * 
         */
        public Builder onVariation(Output<Integer> onVariation) {
            $.onVariation = onVariation;
            return this;
        }

        /**
         * @param onVariation The index of the variation the flag will default to in all new environments when on.
         * 
         * @return builder
         * 
         */
        public Builder onVariation(Integer onVariation) {
            return onVariation(Output.of(onVariation));
        }

        public FeatureFlagDefaultsArgs build() {
            $.offVariation = Objects.requireNonNull($.offVariation, "expected parameter 'offVariation' to be non-null");
            $.onVariation = Objects.requireNonNull($.onVariation, "expected parameter 'onVariation' to be non-null");
            return $;
        }
    }

}
