// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.launchdarkly.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.launchdarkly.inputs.GetFlagTriggerInstructionsArgs;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetFlagTriggerArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetFlagTriggerArgs Empty = new GetFlagTriggerArgs();

    /**
     * Whether the trigger is currently active or not.
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Whether the trigger is currently active or not.
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * The unique key of the environment the flag trigger will work in.
     * 
     */
    @Import(name="envKey", required=true)
    private Output<String> envKey;

    /**
     * @return The unique key of the environment the flag trigger will work in.
     * 
     */
    public Output<String> envKey() {
        return this.envKey;
    }

    /**
     * The unique key of the associated flag.
     * 
     */
    @Import(name="flagKey", required=true)
    private Output<String> flagKey;

    /**
     * @return The unique key of the associated flag.
     * 
     */
    public Output<String> flagKey() {
        return this.flagKey;
    }

    @Import(name="id", required=true)
    private Output<String> id;

    public Output<String> id() {
        return this.id;
    }

    /**
     * Instructions containing the action to perform when invoking the trigger. Currently supported flag actions are `&#34;turnFlagOn&#34;` and `&#34;turnFlagOff&#34;`. These can be found on the `kind` field nested on the `instructions` attribute.
     * 
     */
    @Import(name="instructions")
    private @Nullable Output<GetFlagTriggerInstructionsArgs> instructions;

    /**
     * @return Instructions containing the action to perform when invoking the trigger. Currently supported flag actions are `&#34;turnFlagOn&#34;` and `&#34;turnFlagOff&#34;`. These can be found on the `kind` field nested on the `instructions` attribute.
     * 
     */
    public Optional<Output<GetFlagTriggerInstructionsArgs>> instructions() {
        return Optional.ofNullable(this.instructions);
    }

    /**
     * The unique identifier of the integration your trigger is set up with.
     * 
     */
    @Import(name="integrationKey")
    private @Nullable Output<String> integrationKey;

    /**
     * @return The unique identifier of the integration your trigger is set up with.
     * 
     */
    public Optional<Output<String>> integrationKey() {
        return Optional.ofNullable(this.integrationKey);
    }

    /**
     * The unique key of the project encompassing the associated flag.
     * 
     */
    @Import(name="projectKey", required=true)
    private Output<String> projectKey;

    /**
     * @return The unique key of the project encompassing the associated flag.
     * 
     */
    public Output<String> projectKey() {
        return this.projectKey;
    }

    private GetFlagTriggerArgs() {}

    private GetFlagTriggerArgs(GetFlagTriggerArgs $) {
        this.enabled = $.enabled;
        this.envKey = $.envKey;
        this.flagKey = $.flagKey;
        this.id = $.id;
        this.instructions = $.instructions;
        this.integrationKey = $.integrationKey;
        this.projectKey = $.projectKey;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetFlagTriggerArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetFlagTriggerArgs $;

        public Builder() {
            $ = new GetFlagTriggerArgs();
        }

        public Builder(GetFlagTriggerArgs defaults) {
            $ = new GetFlagTriggerArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Whether the trigger is currently active or not.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Whether the trigger is currently active or not.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param envKey The unique key of the environment the flag trigger will work in.
         * 
         * @return builder
         * 
         */
        public Builder envKey(Output<String> envKey) {
            $.envKey = envKey;
            return this;
        }

        /**
         * @param envKey The unique key of the environment the flag trigger will work in.
         * 
         * @return builder
         * 
         */
        public Builder envKey(String envKey) {
            return envKey(Output.of(envKey));
        }

        /**
         * @param flagKey The unique key of the associated flag.
         * 
         * @return builder
         * 
         */
        public Builder flagKey(Output<String> flagKey) {
            $.flagKey = flagKey;
            return this;
        }

        /**
         * @param flagKey The unique key of the associated flag.
         * 
         * @return builder
         * 
         */
        public Builder flagKey(String flagKey) {
            return flagKey(Output.of(flagKey));
        }

        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param instructions Instructions containing the action to perform when invoking the trigger. Currently supported flag actions are `&#34;turnFlagOn&#34;` and `&#34;turnFlagOff&#34;`. These can be found on the `kind` field nested on the `instructions` attribute.
         * 
         * @return builder
         * 
         */
        public Builder instructions(@Nullable Output<GetFlagTriggerInstructionsArgs> instructions) {
            $.instructions = instructions;
            return this;
        }

        /**
         * @param instructions Instructions containing the action to perform when invoking the trigger. Currently supported flag actions are `&#34;turnFlagOn&#34;` and `&#34;turnFlagOff&#34;`. These can be found on the `kind` field nested on the `instructions` attribute.
         * 
         * @return builder
         * 
         */
        public Builder instructions(GetFlagTriggerInstructionsArgs instructions) {
            return instructions(Output.of(instructions));
        }

        /**
         * @param integrationKey The unique identifier of the integration your trigger is set up with.
         * 
         * @return builder
         * 
         */
        public Builder integrationKey(@Nullable Output<String> integrationKey) {
            $.integrationKey = integrationKey;
            return this;
        }

        /**
         * @param integrationKey The unique identifier of the integration your trigger is set up with.
         * 
         * @return builder
         * 
         */
        public Builder integrationKey(String integrationKey) {
            return integrationKey(Output.of(integrationKey));
        }

        /**
         * @param projectKey The unique key of the project encompassing the associated flag.
         * 
         * @return builder
         * 
         */
        public Builder projectKey(Output<String> projectKey) {
            $.projectKey = projectKey;
            return this;
        }

        /**
         * @param projectKey The unique key of the project encompassing the associated flag.
         * 
         * @return builder
         * 
         */
        public Builder projectKey(String projectKey) {
            return projectKey(Output.of(projectKey));
        }

        public GetFlagTriggerArgs build() {
            $.envKey = Objects.requireNonNull($.envKey, "expected parameter 'envKey' to be non-null");
            $.flagKey = Objects.requireNonNull($.flagKey, "expected parameter 'flagKey' to be non-null");
            $.id = Objects.requireNonNull($.id, "expected parameter 'id' to be non-null");
            $.projectKey = Objects.requireNonNull($.projectKey, "expected parameter 'projectKey' to be non-null");
            return $;
        }
    }

}
