// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.launchdarkly.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetMetricUrl extends com.pulumi.resources.InvokeArgs {

    public static final GetMetricUrl Empty = new GetMetricUrl();

    /**
     * The metric type. Available choices are `click`, `custom`, and `pageview`.
     * 
     */
    @Import(name="kind", required=true)
    private String kind;

    /**
     * @return The metric type. Available choices are `click`, `custom`, and `pageview`.
     * 
     */
    public String kind() {
        return this.kind;
    }

    @Import(name="pattern")
    private @Nullable String pattern;

    public Optional<String> pattern() {
        return Optional.ofNullable(this.pattern);
    }

    @Import(name="substring")
    private @Nullable String substring;

    public Optional<String> substring() {
        return Optional.ofNullable(this.substring);
    }

    @Import(name="url")
    private @Nullable String url;

    public Optional<String> url() {
        return Optional.ofNullable(this.url);
    }

    private GetMetricUrl() {}

    private GetMetricUrl(GetMetricUrl $) {
        this.kind = $.kind;
        this.pattern = $.pattern;
        this.substring = $.substring;
        this.url = $.url;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetMetricUrl defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetMetricUrl $;

        public Builder() {
            $ = new GetMetricUrl();
        }

        public Builder(GetMetricUrl defaults) {
            $ = new GetMetricUrl(Objects.requireNonNull(defaults));
        }

        /**
         * @param kind The metric type. Available choices are `click`, `custom`, and `pageview`.
         * 
         * @return builder
         * 
         */
        public Builder kind(String kind) {
            $.kind = kind;
            return this;
        }

        public Builder pattern(@Nullable String pattern) {
            $.pattern = pattern;
            return this;
        }

        public Builder substring(@Nullable String substring) {
            $.substring = substring;
            return this;
        }

        public Builder url(@Nullable String url) {
            $.url = url;
            return this;
        }

        public GetMetricUrl build() {
            $.kind = Objects.requireNonNull($.kind, "expected parameter 'kind' to be non-null");
            return $;
        }
    }

}
