// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.launchdarkly.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetWebhookStatement extends com.pulumi.resources.InvokeArgs {

    public static final GetWebhookStatement Empty = new GetWebhookStatement();

    @Import(name="actions")
    private @Nullable List<String> actions;

    public Optional<List<String>> actions() {
        return Optional.ofNullable(this.actions);
    }

    /**
     * Either `allow` or `deny`. This argument defines whether the statement allows or denies access to the named resources and actions.
     * 
     */
    @Import(name="effect", required=true)
    private String effect;

    /**
     * @return Either `allow` or `deny`. This argument defines whether the statement allows or denies access to the named resources and actions.
     * 
     */
    public String effect() {
        return this.effect;
    }

    @Import(name="notActions")
    private @Nullable List<String> notActions;

    public Optional<List<String>> notActions() {
        return Optional.ofNullable(this.notActions);
    }

    /**
     * The list of resource specifiers defining the resources to which the statement does not apply. For a list of available resources read [Understanding resource types and scopes](https://docs.launchdarkly.com/home/account-security/custom-roles/resources#understanding-resource-types-and-scopes).
     * 
     */
    @Import(name="notResources")
    private @Nullable List<String> notResources;

    /**
     * @return The list of resource specifiers defining the resources to which the statement does not apply. For a list of available resources read [Understanding resource types and scopes](https://docs.launchdarkly.com/home/account-security/custom-roles/resources#understanding-resource-types-and-scopes).
     * 
     */
    public Optional<List<String>> notResources() {
        return Optional.ofNullable(this.notResources);
    }

    /**
     * The list of resource specifiers defining the resources to which the statement applies. For a list of available resources read [Understanding resource types and scopes](https://docs.launchdarkly.com/home/account-security/custom-roles/resources#understanding-resource-types-and-scopes).
     * 
     */
    @Import(name="resources")
    private @Nullable List<String> resources;

    /**
     * @return The list of resource specifiers defining the resources to which the statement applies. For a list of available resources read [Understanding resource types and scopes](https://docs.launchdarkly.com/home/account-security/custom-roles/resources#understanding-resource-types-and-scopes).
     * 
     */
    public Optional<List<String>> resources() {
        return Optional.ofNullable(this.resources);
    }

    private GetWebhookStatement() {}

    private GetWebhookStatement(GetWebhookStatement $) {
        this.actions = $.actions;
        this.effect = $.effect;
        this.notActions = $.notActions;
        this.notResources = $.notResources;
        this.resources = $.resources;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetWebhookStatement defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetWebhookStatement $;

        public Builder() {
            $ = new GetWebhookStatement();
        }

        public Builder(GetWebhookStatement defaults) {
            $ = new GetWebhookStatement(Objects.requireNonNull(defaults));
        }

        public Builder actions(@Nullable List<String> actions) {
            $.actions = actions;
            return this;
        }

        public Builder actions(String... actions) {
            return actions(List.of(actions));
        }

        /**
         * @param effect Either `allow` or `deny`. This argument defines whether the statement allows or denies access to the named resources and actions.
         * 
         * @return builder
         * 
         */
        public Builder effect(String effect) {
            $.effect = effect;
            return this;
        }

        public Builder notActions(@Nullable List<String> notActions) {
            $.notActions = notActions;
            return this;
        }

        public Builder notActions(String... notActions) {
            return notActions(List.of(notActions));
        }

        /**
         * @param notResources The list of resource specifiers defining the resources to which the statement does not apply. For a list of available resources read [Understanding resource types and scopes](https://docs.launchdarkly.com/home/account-security/custom-roles/resources#understanding-resource-types-and-scopes).
         * 
         * @return builder
         * 
         */
        public Builder notResources(@Nullable List<String> notResources) {
            $.notResources = notResources;
            return this;
        }

        /**
         * @param notResources The list of resource specifiers defining the resources to which the statement does not apply. For a list of available resources read [Understanding resource types and scopes](https://docs.launchdarkly.com/home/account-security/custom-roles/resources#understanding-resource-types-and-scopes).
         * 
         * @return builder
         * 
         */
        public Builder notResources(String... notResources) {
            return notResources(List.of(notResources));
        }

        /**
         * @param resources The list of resource specifiers defining the resources to which the statement applies. For a list of available resources read [Understanding resource types and scopes](https://docs.launchdarkly.com/home/account-security/custom-roles/resources#understanding-resource-types-and-scopes).
         * 
         * @return builder
         * 
         */
        public Builder resources(@Nullable List<String> resources) {
            $.resources = resources;
            return this;
        }

        /**
         * @param resources The list of resource specifiers defining the resources to which the statement applies. For a list of available resources read [Understanding resource types and scopes](https://docs.launchdarkly.com/home/account-security/custom-roles/resources#understanding-resource-types-and-scopes).
         * 
         * @return builder
         * 
         */
        public Builder resources(String... resources) {
            return resources(List.of(resources));
        }

        public GetWebhookStatement build() {
            $.effect = Objects.requireNonNull($.effect, "expected parameter 'effect' to be non-null");
            return $;
        }
    }

}
