// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.launchdarkly.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.launchdarkly.inputs.RelayProxyConfigurationPolicyArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RelayProxyConfigurationState extends com.pulumi.resources.ResourceArgs {

    public static final RelayProxyConfigurationState Empty = new RelayProxyConfigurationState();

    /**
     * The last 4 characters of the Relay Proxy configuration&#39;s unique key.
     * 
     */
    @Import(name="displayKey")
    private @Nullable Output<String> displayKey;

    /**
     * @return The last 4 characters of the Relay Proxy configuration&#39;s unique key.
     * 
     */
    public Optional<Output<String>> displayKey() {
        return Optional.ofNullable(this.displayKey);
    }

    /**
     * The Relay Proxy configuration&#39;s unique key. Because the `full_key` is only exposed upon creation, it will not be available if the resource is imported.
     * 
     */
    @Import(name="fullKey")
    private @Nullable Output<String> fullKey;

    /**
     * @return The Relay Proxy configuration&#39;s unique key. Because the `full_key` is only exposed upon creation, it will not be available if the resource is imported.
     * 
     */
    public Optional<Output<String>> fullKey() {
        return Optional.ofNullable(this.fullKey);
    }

    /**
     * The human-readable name for your Relay Proxy configuration.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The human-readable name for your Relay Proxy configuration.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The Relay Proxy configuration&#39;s rule policy block. This determines what content the Relay Proxy receives. To learn more, read [Understanding policies](https://docs.launchdarkly.com/home/members/role-policies#understanding-policies).
     * 
     */
    @Import(name="policies")
    private @Nullable Output<List<RelayProxyConfigurationPolicyArgs>> policies;

    /**
     * @return The Relay Proxy configuration&#39;s rule policy block. This determines what content the Relay Proxy receives. To learn more, read [Understanding policies](https://docs.launchdarkly.com/home/members/role-policies#understanding-policies).
     * 
     */
    public Optional<Output<List<RelayProxyConfigurationPolicyArgs>>> policies() {
        return Optional.ofNullable(this.policies);
    }

    private RelayProxyConfigurationState() {}

    private RelayProxyConfigurationState(RelayProxyConfigurationState $) {
        this.displayKey = $.displayKey;
        this.fullKey = $.fullKey;
        this.name = $.name;
        this.policies = $.policies;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RelayProxyConfigurationState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RelayProxyConfigurationState $;

        public Builder() {
            $ = new RelayProxyConfigurationState();
        }

        public Builder(RelayProxyConfigurationState defaults) {
            $ = new RelayProxyConfigurationState(Objects.requireNonNull(defaults));
        }

        /**
         * @param displayKey The last 4 characters of the Relay Proxy configuration&#39;s unique key.
         * 
         * @return builder
         * 
         */
        public Builder displayKey(@Nullable Output<String> displayKey) {
            $.displayKey = displayKey;
            return this;
        }

        /**
         * @param displayKey The last 4 characters of the Relay Proxy configuration&#39;s unique key.
         * 
         * @return builder
         * 
         */
        public Builder displayKey(String displayKey) {
            return displayKey(Output.of(displayKey));
        }

        /**
         * @param fullKey The Relay Proxy configuration&#39;s unique key. Because the `full_key` is only exposed upon creation, it will not be available if the resource is imported.
         * 
         * @return builder
         * 
         */
        public Builder fullKey(@Nullable Output<String> fullKey) {
            $.fullKey = fullKey;
            return this;
        }

        /**
         * @param fullKey The Relay Proxy configuration&#39;s unique key. Because the `full_key` is only exposed upon creation, it will not be available if the resource is imported.
         * 
         * @return builder
         * 
         */
        public Builder fullKey(String fullKey) {
            return fullKey(Output.of(fullKey));
        }

        /**
         * @param name The human-readable name for your Relay Proxy configuration.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The human-readable name for your Relay Proxy configuration.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param policies The Relay Proxy configuration&#39;s rule policy block. This determines what content the Relay Proxy receives. To learn more, read [Understanding policies](https://docs.launchdarkly.com/home/members/role-policies#understanding-policies).
         * 
         * @return builder
         * 
         */
        public Builder policies(@Nullable Output<List<RelayProxyConfigurationPolicyArgs>> policies) {
            $.policies = policies;
            return this;
        }

        /**
         * @param policies The Relay Proxy configuration&#39;s rule policy block. This determines what content the Relay Proxy receives. To learn more, read [Understanding policies](https://docs.launchdarkly.com/home/members/role-policies#understanding-policies).
         * 
         * @return builder
         * 
         */
        public Builder policies(List<RelayProxyConfigurationPolicyArgs> policies) {
            return policies(Output.of(policies));
        }

        /**
         * @param policies The Relay Proxy configuration&#39;s rule policy block. This determines what content the Relay Proxy receives. To learn more, read [Understanding policies](https://docs.launchdarkly.com/home/members/role-policies#understanding-policies).
         * 
         * @return builder
         * 
         */
        public Builder policies(RelayProxyConfigurationPolicyArgs... policies) {
            return policies(List.of(policies));
        }

        public RelayProxyConfigurationState build() {
            return $;
        }
    }

}
