// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.launchdarkly.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.launchdarkly.inputs.SegmentRuleClauseArgs;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SegmentRuleArgs extends com.pulumi.resources.ResourceArgs {

    public static final SegmentRuleArgs Empty = new SegmentRuleArgs();

    /**
     * The attribute by which to group users together.
     * 
     */
    @Import(name="bucketBy")
    private @Nullable Output<String> bucketBy;

    /**
     * @return The attribute by which to group users together.
     * 
     */
    public Optional<Output<String>> bucketBy() {
        return Optional.ofNullable(this.bucketBy);
    }

    /**
     * List of nested custom rule clause blocks. To learn more, read Nested Clauses Blocks.
     * 
     */
    @Import(name="clauses")
    private @Nullable Output<List<SegmentRuleClauseArgs>> clauses;

    /**
     * @return List of nested custom rule clause blocks. To learn more, read Nested Clauses Blocks.
     * 
     */
    public Optional<Output<List<SegmentRuleClauseArgs>>> clauses() {
        return Optional.ofNullable(this.clauses);
    }

    /**
     * The integer weight of the rule (between 1 and 100000).
     * 
     */
    @Import(name="weight")
    private @Nullable Output<Integer> weight;

    /**
     * @return The integer weight of the rule (between 1 and 100000).
     * 
     */
    public Optional<Output<Integer>> weight() {
        return Optional.ofNullable(this.weight);
    }

    private SegmentRuleArgs() {}

    private SegmentRuleArgs(SegmentRuleArgs $) {
        this.bucketBy = $.bucketBy;
        this.clauses = $.clauses;
        this.weight = $.weight;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SegmentRuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SegmentRuleArgs $;

        public Builder() {
            $ = new SegmentRuleArgs();
        }

        public Builder(SegmentRuleArgs defaults) {
            $ = new SegmentRuleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param bucketBy The attribute by which to group users together.
         * 
         * @return builder
         * 
         */
        public Builder bucketBy(@Nullable Output<String> bucketBy) {
            $.bucketBy = bucketBy;
            return this;
        }

        /**
         * @param bucketBy The attribute by which to group users together.
         * 
         * @return builder
         * 
         */
        public Builder bucketBy(String bucketBy) {
            return bucketBy(Output.of(bucketBy));
        }

        /**
         * @param clauses List of nested custom rule clause blocks. To learn more, read Nested Clauses Blocks.
         * 
         * @return builder
         * 
         */
        public Builder clauses(@Nullable Output<List<SegmentRuleClauseArgs>> clauses) {
            $.clauses = clauses;
            return this;
        }

        /**
         * @param clauses List of nested custom rule clause blocks. To learn more, read Nested Clauses Blocks.
         * 
         * @return builder
         * 
         */
        public Builder clauses(List<SegmentRuleClauseArgs> clauses) {
            return clauses(Output.of(clauses));
        }

        /**
         * @param clauses List of nested custom rule clause blocks. To learn more, read Nested Clauses Blocks.
         * 
         * @return builder
         * 
         */
        public Builder clauses(SegmentRuleClauseArgs... clauses) {
            return clauses(List.of(clauses));
        }

        /**
         * @param weight The integer weight of the rule (between 1 and 100000).
         * 
         * @return builder
         * 
         */
        public Builder weight(@Nullable Output<Integer> weight) {
            $.weight = weight;
            return this;
        }

        /**
         * @param weight The integer weight of the rule (between 1 and 100000).
         * 
         * @return builder
         * 
         */
        public Builder weight(Integer weight) {
            return weight(Output.of(weight));
        }

        public SegmentRuleArgs build() {
            return $;
        }
    }

}
