// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Launchdarkly.Outputs
{

    [OutputType]
    public sealed class FeatureFlagEnvironmentRule
    {
        /// <summary>
        /// Group percentage rollout by a custom attribute. This argument is only valid if `rollout_weights` is also specified.
        /// </summary>
        public readonly string? BucketBy;
        /// <summary>
        /// List of nested blocks specifying the logical clauses to evaluate. To learn more, read Nested Clauses Blocks.
        /// </summary>
        public readonly ImmutableArray<Outputs.FeatureFlagEnvironmentRuleClause> Clauses;
        /// <summary>
        /// List of integer percentage rollout weights (in thousandths of a percent) to apply to each variation if the rule clauses evaluates to `true`. The sum of the `rollout_weights` must equal 100000. You must specify either `variation` or `rollout_weights`.
        /// </summary>
        public readonly ImmutableArray<int> RolloutWeights;
        /// <summary>
        /// The integer variation index to serve if the rule clauses evaluate to `true`. You must specify either `variation` or `rollout_weights`.
        /// </summary>
        public readonly int? Variation;

        [OutputConstructor]
        private FeatureFlagEnvironmentRule(
            string? bucketBy,

            ImmutableArray<Outputs.FeatureFlagEnvironmentRuleClause> clauses,

            ImmutableArray<int> rolloutWeights,

            int? variation)
        {
            BucketBy = bucketBy;
            Clauses = clauses;
            RolloutWeights = rolloutWeights;
            Variation = variation;
        }
    }
}
