// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Launchdarkly.Outputs
{

    [OutputType]
    public sealed class MetricUrl
    {
        /// <summary>
        /// The URL type. Available choices are `exact`, `canonical`, `substring` and `regex`.
        /// </summary>
        public readonly string Kind;
        /// <summary>
        /// The regex pattern to match by.
        /// </summary>
        public readonly string? Pattern;
        /// <summary>
        /// The URL substring to match by.
        /// </summary>
        public readonly string? Substring;
        /// <summary>
        /// The exact or canonical URL.
        /// </summary>
        public readonly string? Url;

        [OutputConstructor]
        private MetricUrl(
            string kind,

            string? pattern,

            string? substring,

            string? url)
        {
            Kind = kind;
            Pattern = pattern;
            Substring = substring;
            Url = url;
        }
    }
}
