// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Launchdarkly.Outputs
{

    [OutputType]
    public sealed class ProjectDefaultClientSideAvailability
    {
        /// <summary>
        /// Whether feature flags created under the project are available to JavaScript SDKs using the client-side ID by default. Defaults to `false` when not using `default_client_side_availability`.
        /// </summary>
        public readonly bool UsingEnvironmentId;
        /// <summary>
        /// Whether feature flags created under the project are available to mobile SDKs, and other non-JavaScript SDKs, using a mobile key by default. Defaults to `true` when not using `default_client_side_availability`.
        /// </summary>
        public readonly bool UsingMobileKey;

        [OutputConstructor]
        private ProjectDefaultClientSideAvailability(
            bool usingEnvironmentId,

            bool usingMobileKey)
        {
            UsingEnvironmentId = usingEnvironmentId;
            UsingMobileKey = usingMobileKey;
        }
    }
}
