// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Launchdarkly.Inputs
{

    public sealed class FlagTriggerInstructionsArgs : global::Pulumi.ResourceArgs
    {
        [Input("kind", required: true)]
        public Input<string> Kind { get; set; } = null!;

        public FlagTriggerInstructionsArgs()
        {
        }
        public static new FlagTriggerInstructionsArgs Empty => new FlagTriggerInstructionsArgs();
    }
}
