// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Launchdarkly.Inputs
{

    public sealed class GetFeatureFlagEnvironmentRuleClauseArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The user attribute operated on.
        /// </summary>
        [Input("attribute", required: true)]
        public string Attribute { get; set; } = null!;

        /// <summary>
        /// Whether the rule clause is negated.
        /// </summary>
        [Input("negate")]
        public bool? Negate { get; set; }

        /// <summary>
        /// The operator associated with the rule clause. This will be one of `in`, `endsWith`, `startsWith`, `matches`, `contains`, `lessThan`, `lessThanOrEqual`, `greaterThanOrEqual`, `before`, `after`, `segmentMatch`, `semVerEqual`, `semVerLessThan`, and `semVerGreaterThan`.
        /// </summary>
        [Input("op", required: true)]
        public string Op { get; set; } = null!;

        /// <summary>
        /// The type for each of the clause's values. Available types are `boolean`, `string`, and `number`.
        /// </summary>
        [Input("valueType")]
        public string? ValueType { get; set; }

        [Input("values", required: true)]
        private List<string>? _values;

        /// <summary>
        /// The list of values associated with the rule clause.
        /// </summary>
        public List<string> Values
        {
            get => _values ?? (_values = new List<string>());
            set => _values = value;
        }

        public GetFeatureFlagEnvironmentRuleClauseArgs()
        {
        }
        public static new GetFeatureFlagEnvironmentRuleClauseArgs Empty => new GetFeatureFlagEnvironmentRuleClauseArgs();
    }
}
