// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Launchdarkly.Inputs
{

    public sealed class GetMetricUrlArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The metric type. Available choices are `click`, `custom`, and `pageview`.
        /// </summary>
        [Input("kind", required: true)]
        public string Kind { get; set; } = null!;

        [Input("pattern")]
        public string? Pattern { get; set; }

        [Input("substring")]
        public string? Substring { get; set; }

        [Input("url")]
        public string? Url { get; set; }

        public GetMetricUrlArgs()
        {
        }
        public static new GetMetricUrlArgs Empty => new GetMetricUrlArgs();
    }
}
