// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.launchdarkly;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.launchdarkly.TeamMemberArgs;
import com.pulumi.launchdarkly.Utilities;
import com.pulumi.launchdarkly.inputs.TeamMemberState;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides a LaunchDarkly team member resource.
 * 
 * This resource allows you to create and manage team members within your LaunchDarkly organization.
 * 
 * &gt; **Note:** You can only manage team members with &#34;admin&#34; level personal access tokens. To learn more, read [Managing Teams](https://docs.launchdarkly.com/docs/teams/managing).
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.launchdarkly.TeamMember;
 * import com.pulumi.launchdarkly.TeamMemberArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new TeamMember(&#34;example&#34;, TeamMemberArgs.builder()        
 *             .email(&#34;example.user@example.com&#34;)
 *             .firstName(&#34;John&#34;)
 *             .lastName(&#34;Smith&#34;)
 *             .role(&#34;writer&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * LaunchDarkly team members can be imported using the team member&#39;s 24 character ID, e.g.
 * 
 * ```sh
 *  $ pulumi import launchdarkly:index/teamMember:TeamMember example 5f05565b48be0b441fb63020
 * ```
 * 
 */
@ResourceType(type="launchdarkly:index/teamMember:TeamMember")
public class TeamMember extends com.pulumi.resources.CustomResource {
    /**
     * The list of custom roles keys associated with the team member. Custom roles are only available to customers on enterprise plans. To learn more about enterprise plans, contact sales@launchdarkly.com.
     * 
     */
    @Export(name="customRoles", type=List.class, parameters={String.class})
    private Output</* @Nullable */ List<String>> customRoles;

    /**
     * @return The list of custom roles keys associated with the team member. Custom roles are only available to customers on enterprise plans. To learn more about enterprise plans, contact sales@launchdarkly.com.
     * 
     */
    public Output<Optional<List<String>>> customRoles() {
        return Codegen.optional(this.customRoles);
    }
    /**
     * The unique email address associated with the team member. A change in this field will force the destruction of the existing resource and the creation of a new one.
     * 
     */
    @Export(name="email", type=String.class, parameters={})
    private Output<String> email;

    /**
     * @return The unique email address associated with the team member. A change in this field will force the destruction of the existing resource and the creation of a new one.
     * 
     */
    public Output<String> email() {
        return this.email;
    }
    /**
     * The team member&#39;s given name. Please note that, once created, this cannot be updated except by the team member themself.
     * 
     */
    @Export(name="firstName", type=String.class, parameters={})
    private Output</* @Nullable */ String> firstName;

    /**
     * @return The team member&#39;s given name. Please note that, once created, this cannot be updated except by the team member themself.
     * 
     */
    public Output<Optional<String>> firstName() {
        return Codegen.optional(this.firstName);
    }
    /**
     * The team member&#39;s family name. Please note that, once created, this cannot be updated except by the team member themself.
     * 
     */
    @Export(name="lastName", type=String.class, parameters={})
    private Output</* @Nullable */ String> lastName;

    /**
     * @return The team member&#39;s family name. Please note that, once created, this cannot be updated except by the team member themself.
     * 
     */
    public Output<Optional<String>> lastName() {
        return Codegen.optional(this.lastName);
    }
    /**
     * The role associated with team member. Supported roles are `reader`, `writer`, `no_access`, or `admin`. If you don&#39;t specify a role, `reader` is assigned by default.
     * 
     */
    @Export(name="role", type=String.class, parameters={})
    private Output<String> role;

    /**
     * @return The role associated with team member. Supported roles are `reader`, `writer`, `no_access`, or `admin`. If you don&#39;t specify a role, `reader` is assigned by default.
     * 
     */
    public Output<String> role() {
        return this.role;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public TeamMember(String name) {
        this(name, TeamMemberArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public TeamMember(String name, TeamMemberArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public TeamMember(String name, TeamMemberArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("launchdarkly:index/teamMember:TeamMember", name, args == null ? TeamMemberArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private TeamMember(String name, Output<String> id, @Nullable TeamMemberState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("launchdarkly:index/teamMember:TeamMember", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static TeamMember get(String name, Output<String> id, @Nullable TeamMemberState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new TeamMember(name, id, state, options);
    }
}
