// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides a LaunchDarkly project data source.
 *
 * This data source allows you to retrieve project information from your LaunchDarkly organization.
 *
 * > **Note:** LaunchDarkly data sources do not provide access to the project's environments. If you wish to import environment configurations as data sources you must use the [`launchdarkly.Environment` data source](https://www.terraform.io/docs/providers/launchdarkly/d/environment.html).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as launchdarkly from "@pulumi/launchdarkly";
 *
 * const example = pulumi.output(launchdarkly.getProject({
 *     key: "example-project",
 * }));
 * ```
 */
export function getProject(args: GetProjectArgs, opts?: pulumi.InvokeOptions): Promise<GetProjectResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("launchdarkly:index/getProject:getProject", {
        "key": args.key,
        "tags": args.tags,
    }, opts);
}

/**
 * A collection of arguments for invoking getProject.
 */
export interface GetProjectArgs {
    /**
     * The project's unique key.
     */
    key: string;
    /**
     * The project's set of tags.
     */
    tags?: string[];
}

/**
 * A collection of values returned by getProject.
 */
export interface GetProjectResult {
    /**
     * **Deprecated** A map describing which client-side SDKs can use new flags by default. To learn more, read Nested Client-Side Availability Block.
     * Please migrate to `defaultClientSideAvailability` to maintain future compatability.
     *
     * @deprecated 'client_side_availability' is now deprecated. Please migrate to 'default_client_side_availability' to maintain future compatability.
     */
    readonly clientSideAvailabilities: outputs.GetProjectClientSideAvailability[];
    /**
     * A block describing which client-side SDKs can use new flags by default. To learn more, read Nested Client-Side Availability Block.
     */
    readonly defaultClientSideAvailabilities: outputs.GetProjectDefaultClientSideAvailability[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly key: string;
    /**
     * The project's name.
     */
    readonly name: string;
    /**
     * The project's set of tags.
     */
    readonly tags?: string[];
}

export function getProjectOutput(args: GetProjectOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetProjectResult> {
    return pulumi.output(args).apply(a => getProject(a, opts))
}

/**
 * A collection of arguments for invoking getProject.
 */
export interface GetProjectOutputArgs {
    /**
     * The project's unique key.
     */
    key: pulumi.Input<string>;
    /**
     * The project's set of tags.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
}
